# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name='商品分类ID')),
                ('typename', models.CharField(max_length=32, verbose_name='商品分类名称')),
                ('childtypenames', models.CharField(max_length=255, verbose_name='子分类名称')),
                ('typesort', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'db_table': 'axf_foodtype',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(verbose_name='商品ID')),
                ('productimg', models.CharField(max_length=255, verbose_name='商品图片信息')),
                ('productname', models.CharField(max_length=128, verbose_name='商品名称')),
                ('productlongname', models.CharField(max_length=255, verbose_name='商品详细名称')),
                ('specifics', models.CharField(max_length=64, verbose_name='商品规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格')),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品市场价格')),
                ('categoryid', models.IntegerField(verbose_name='所属分类ID')),
                ('childcid', models.IntegerField(verbose_name='所属子分类ID')),
                ('childcidname', models.CharField(max_length=128, verbose_name='商品子分类名称')),
                ('storenums', models.IntegerField(verbose_name='商品库存')),
                ('productnum', models.IntegerField(verbose_name='商品销量')),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
